[package]
name = "reticle"
version = "0.1.0"
authors = ["Luis Vega <vegaluis@cs.washington.edu>"]
edition = "2018"

[dependencies]
pretty = "0.10.0"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
petgraph = "0.5.1"
regex = "1.3.9"
pest = "2.0"
pest_derive = "2.0"
pest_consume = "1.0.5"
vast = { git = "https://github.com/vegaluisjose/vast.git", rev = "e65bf0567b715f58d50b0fe36747576b0fd5153f" }
