[package]
name = "reticle"
version = "0.1.0"
authors = ["Luis Vega <vegaluis@cs.washington.edu>"]
edition = "2018"

[dependencies]
pretty = "0.10.0"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
petgraph = "0.5.1"
