[package]
name = "prim"
version = "0.1.0"
authors = ["The Reticle developers"]
license = "Apache-2.0"
edition = "2018"

[dependencies]
derive_more = { version = "0.99.0", features = ["from", "deref", "deref_mut"] }
