name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Reticle ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install 1.5.0
        uses: actions-rs/toolchain@v1
        with:
            toolchain: 1.5.0
            override: true
            components: rustfmt, clippy
      - name: Check format
        uses: actions-rs/cargo@v1
        with:
          command: fmt --all -- --check
